# Generated by Django 2.2.3 on 2019-08-23 21:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_count', models.IntegerField(blank=True, null=True)),
                ('rating_count', models.IntegerField(blank=True, null=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('u', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tchr_info', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_count', models.IntegerField(blank=True, null=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('u', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stdnt_info', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SearchCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=200, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('u', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_srch_code', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('accessed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accessed_code', to=settings.AUTH_USER_MODEL)),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='s_code', to='capchine.SearchCode')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('my_role', models.CharField(blank=True, choices=[('student', 'Student'), ('teacher', 'Teacher')], max_length=50, null=True)),
                ('u', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='roly', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RatingCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=200, null=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('u', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_rating', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('attention', models.IntegerField(blank=True, null=True)),
                ('performance', models.IntegerField(blank=True, null=True)),
                ('punctuality', models.IntegerField(blank=True, null=True)),
                ('cooperation', models.IntegerField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_code', to='capchine.RatingCode')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='given_rating', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
